### ISSUE TITLE
multipolygon bug

### ISSUE THREAD

**Issue by christophemacabiau** [mapbox/shp-write#17]
I think there is a bug with multipolygon shapes, I started from example/test_multiple_poly.js
Open the generated shape in qgis you will see that there is a problem...
Is there something wrong in my code ?

``` javascript
var write = require('shp-write').write,
    fs = require('fs');

var features = [];
var points = [];
for (var i=0; i<3; i++) {
  features.push({id: i});
  points.push([[i, 0], [i, 1], [i+1, 1], [i+1, 0], [i, 0]]);
};

console.log(features);
console.log(points);

function finish(err, files) {
    fs.writeFileSync('polygon.shp', toBuffer(files.shp.buffer));
    fs.writeFileSync('polygon.shx', toBuffer(files.shx.buffer));
    fs.writeFileSync('polygon.dbf', toBuffer(files.dbf.buffer));
    fs.writeFileSync('polygon.prj', files.prj);
}

function toBuffer(ab) {
    var buffer = new Buffer(ab.byteLength),
        view = new Uint8Array(ab);
    for (var i = 0; i < buffer.length; ++i) { buffer[i] = view[i]; }
    return buffer;
}

write(
    // feature data
    features,
    // geometry type
    'POLYGON',
    // geometries
    points,
    finish);
```

**Comment by jseppi** [comment]
Your `for` loop only generates 3 points but you are writing feature data of length 5

**Comment by cricri** [comment]
sorry!
I have updated the code

**Comment by galharth** [comment]
@cricri Have you solved this problem?

**Comment by cricri** [comment]
nope :-(

**Comment by gxcodes** [comment]
@tmcw 

Hi, is there any update on this problem? I use shpwrite.zip method and the shapefile produced joins all the polygon, and seems to only add one last feature.properties

I still face it and have been scratching my head over it. Any direction to fix this?

**Comment by cricri** [comment]
maybe you can use https://github.com/naturalatlas/node-gdal, which works fine for my use case

**Comment by gxcodes** [comment]
Thanks for the link, will definitely check it out. Hopefully it doesn't need any native dependencies as I'm developing a multi-platform app with electron.

**Comment by tmcw** [comment]
I no longer maintain this module - contact Mapbox for assistance or support.

**Comment by gxcodes** [comment]
Hi @cricri do you have sample usage for the node-gdal link? This multipolygon bug is a real bummer. I'm stuck with an empty zip file if I try to save a multipolygon shape.

**Comment by cricri** [comment]
Hi @gxcodes, I added an example to create a shape using node-gdal
https://github.com/naturalatlas/node-gdal/pull/205/commits/870b44b45075f41f7eae325b077392f5bada1aa5

**Comment by gxcodes** [comment]
@cricri thanks a lot! Really appreciate it.

**Comment by serifea** [comment]
I have a problem also multipolygon!!!!

I download polygon but coudn't for multipolygon

Is there any UPDATE????

Pllsss help !!!

**Comment by hwbllmnn** [comment]
#65 possibly fixes your problem.

**Comment by chwahab** [comment]
Use Turf.js and flat your GeoJSON. 
```shpwrite.download(turf.flatten(geojson))```
